services:

  orchestrator:
    image: omotes-orchestrator-dev
    build:
      context: ..
      dockerfile: orchestrator/dev.Dockerfile
  
  deploy_optimizer:
    image: omotes-optimizer-dev
    build:
      context: ..
      dockerfile: optimizer-worker/dev.Dockerfile
