-- create databases
CREATE DATABASE :PG_DB_JOBS;
CREATE DATABASE :PG_DB_TIMESERIES;

-- create roles
CREATE ROLE :JOBS_RW_USER_NAME LOGIN PASSWORD :'JOBS_RW_USER_PASSWORD';
CREATE ROLE :TIMESERIES_RW_USER_NAME LOGIN PASSWORD :'TIMESERIES_RW_USER_PASSWORD';
ALTER ROLE :TIMESERIES_RW_USER_NAME CREATEDB;
CREATE ROLE :TIMESERIES_RO_USER_NAME LOGIN PASSWORD :'TIMESERIES_RO_USER_PASSWORD';

-- Template privileges for databases created later by TIMESERIES_RW_USER_NAME.
-- New databases created with default CREATE DATABASE settings inherit from template1.
\connect template1
GRANT USAGE ON SCHEMA public TO :TIMESERIES_RO_USER_NAME;
ALTER DEFAULT PRIVILEGES FOR ROLE :TIMESERIES_RW_USER_NAME IN SCHEMA public
	GRANT SELECT ON TABLES TO :TIMESERIES_RO_USER_NAME;

-- DB1
\connect :PG_DB_JOBS

-- Make RW user owner
ALTER DATABASE :PG_DB_JOBS OWNER TO :JOBS_RW_USER_NAME;
ALTER SCHEMA public OWNER TO :JOBS_RW_USER_NAME;

-- Ensure RW can create objects
GRANT ALL ON SCHEMA public TO :JOBS_RW_USER_NAME;

-- Existing objects
GRANT ALL ON ALL TABLES IN SCHEMA public TO :JOBS_RW_USER_NAME;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO :JOBS_RW_USER_NAME;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO :JOBS_RW_USER_NAME;

-- Default privileges
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO :JOBS_RW_USER_NAME;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO :JOBS_RW_USER_NAME;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO :JOBS_RW_USER_NAME;

-- DB2
\connect :PG_DB_TIMESERIES

-- Make RW owner
ALTER DATABASE :PG_DB_TIMESERIES OWNER TO :TIMESERIES_RW_USER_NAME;
ALTER SCHEMA public OWNER TO :TIMESERIES_RW_USER_NAME;

-- Schema privileges
GRANT CONNECT ON DATABASE :PG_DB_TIMESERIES TO :TIMESERIES_RO_USER_NAME;
GRANT ALL ON SCHEMA public TO :TIMESERIES_RW_USER_NAME;
GRANT USAGE ON SCHEMA public TO :TIMESERIES_RO_USER_NAME;

-- Existing objects
GRANT ALL ON ALL TABLES IN SCHEMA public TO :TIMESERIES_RW_USER_NAME;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO :TIMESERIES_RW_USER_NAME;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO :TIMESERIES_RW_USER_NAME;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO :TIMESERIES_RO_USER_NAME;

-- Default privileges
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO :TIMESERIES_RW_USER_NAME;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO :TIMESERIES_RW_USER_NAME;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO :TIMESERIES_RW_USER_NAME;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO :TIMESERIES_RO_USER_NAME;
